import './ContextBriefPanel.css'

const FILE_TYPE_LABELS = { excel: 'Excel', word: 'Word', figma: 'Figma' }
const FILE_TYPE_COLORS = { excel: '#217346', word: '#2B579A', figma: '#1E1E1E' }
const FILE_TYPE_LETTERS = { excel: 'X', word: 'W', figma: 'F' }

const TONE_LABELS = { blocking: 'Blocking', atrisk: 'At risk', upcoming: 'Upcoming' }

function FileIcon({ type }) {
  return (
    <div
      className="cbp-file-icon"
      style={{ background: FILE_TYPE_COLORS[type] || '#888' }}
    >
      {FILE_TYPE_LETTERS[type] || '?'}
    </div>
  )
}

export default function ContextBriefPanel({ brief }) {
  if (!brief) return null

  return (
    <div className="cbp-root">
      {/* Document header */}
      <div className="cbp-doc-header">
        <div className="cbp-doc-title-row">
          <svg className="cbp-md-icon" viewBox="0 0 20 20" fill="none">
            <rect x="3" y="2" width="14" height="16" rx="2" stroke="#6264A7" strokeWidth="1.5"/>
            <path d="M6 6h8M6 9.5h8M6 13h5" stroke="#6264A7" strokeWidth="1.5" strokeLinecap="round"/>
          </svg>
          <span className="cbp-doc-filename">{brief.filename}</span>
        </div>
        <div className="cbp-doc-meta">
          Generated by <strong>{brief.generatedBy}</strong> · {brief.generatedAt} · Based on {brief.basedOn}
        </div>
      </div>

      <div className="cbp-body">

        {/* Team table */}
        <section className="cbp-section">
          <h2 className="cbp-h2">Team</h2>
          <table className="cbp-table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Role</th>
                <th>Owns</th>
              </tr>
            </thead>
            <tbody>
              {brief.team.map((p, i) => (
                <tr key={i}>
                  <td>
                    <div className="cbp-person-cell">
                      <div className="cbp-avatar" style={{ background: p.color }}>{p.initials}</div>
                      <span className="cbp-person-name">{p.name}</span>
                    </div>
                  </td>
                  <td className="cbp-role-cell">{p.role}</td>
                  <td className="cbp-owns-cell">{p.owns}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Open items */}
        <section className="cbp-section">
          <h2 className="cbp-h2">Open items</h2>
          <div className="cbp-open-items">
            {brief.openItems.map((item, i) => (
              <div key={i} className="cbp-open-item">
                <div className="cbp-open-item-header">
                  <span className={`cbp-badge cbp-badge-${item.tone}`}>{TONE_LABELS[item.tone]}</span>
                  <span className="cbp-open-item-label">{item.label}</span>
                  <span className="cbp-open-item-title">{item.title}</span>
                </div>
                <p className="cbp-open-item-detail">{item.detail}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Tools */}
        <section className="cbp-section">
          <h2 className="cbp-h2">Tools in use</h2>
          <div className="cbp-chips">
            {brief.tools.map((t, i) => (
              <span key={i} className="cbp-chip">{t}</span>
            ))}
          </div>
        </section>

        {/* Files */}
        <section className="cbp-section">
          <h2 className="cbp-h2">Files shared</h2>
          <div className="cbp-files">
            {brief.files.map((f, i) => (
              <div key={i} className="cbp-file-row">
                <FileIcon type={f.type} />
                <div className="cbp-file-text">
                  <div className="cbp-file-name">{f.name}.{f.type === 'figma' ? 'fig' : f.type === 'excel' ? 'xlsx' : 'docx'}</div>
                  <div className="cbp-file-meta">{FILE_TYPE_LABELS[f.type]} · {f.owner} · {f.note}</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Key decisions */}
        <section className="cbp-section">
          <h2 className="cbp-h2">Key decisions</h2>
          <ul className="cbp-decisions">
            {brief.decisions.map((d, i) => (
              <li key={i} className="cbp-decision">
                <span className="cbp-decision-date">{d.date}</span>
                <span className="cbp-decision-text">{d.text}</span>
              </li>
            ))}
          </ul>
        </section>

      </div>
    </div>
  )
}
